export enum gameReducerCases {
  SET_SOCKET = "SET_SOCKET",
  SET_ROOM_ID = "SET_ROOM_ID",
  SET_PLAYER_ID = "SET_PLAYER_ID",
  SET_GAME_STATE = "SET_GAME_STATE",
  SET_PLAYERS = "SET_PLAYERS",
  SET_ITEMS = "SET_ITEMS",
  SET_PLAYLISTS = "SET_PLAYLISTS",
  SET_IS_DRAGGING = "SET_IS_DRAGGING",
}