export enum gameReducerCases {
  SET_GAME_STATUS = "SET_GAME_STATUS",
  SET_ITEMS = "SET_ITEMS",
  SET_CURRENT_CARD_ID = "SET_CURRENT_CARD_ID",
  SET_CURRENT_CARD_STATUS = "SET_CURRENT_CARD_STATUS",
  SET_CURRENT_PLAYER_ID = "SET_CURRENT_PLAYER_ID",
}