package interfaces.dto.responseDto;

public enum EventResponseStatus {
    ROOM_ID,
    ROOM_STATE,
    UNAUTHORIZED_ACCESS_TOKEN,
    INVALID_GAME_STATUS,
    PLAYER_HOST_CANNOT_BE_REMOVED,
    PLAYER_NAME_ALREADY_EXISTS,
    PLAYER_COLOR_ALREADY_EXISTS,
    PLAYER_ALREADY_IN_ROOM,
    PLAYLIST_ALREADY_IN_ROOM,
    ROOM_NOT_FOUND,
    PLAYER_NOT_FOUND,
    PLAYLIST_NOT_FOUND,
}
