export enum reducerCases {
  SET_SOCKET = "SET_SOCKET",
  SET_GAME_STATE = "SET_GAME_STATE",
  SET_PLAYERS = "SET_PLAYERS",
  SET_ACTIVE_PLAYER = "SET_ACTIVE_PLAYER",
  SET_ITEMS = "SET_ITEMS",
  SET_ACTIVE_CARD = "SET_ACTIVE_CARD",
}
