export enum reducerCases {
  SET_SPOTIFY_TOKEN = "SET_SPOTIFY_TOKEN",
  SET_SOCKET = "SET_SOCKET",
  SET_PLAYERS = "SET_PLAYERS",
  SET_ACTIVE_PLAYER = "SET_ACTIVE_PLAYER",
  SET_ITEMS = "SET_ITEMS",
  SET_ACTIVE_CARD = "SET_ACTIVE_CARD",
}
