export enum reducerCases {
  SET_SOCKET = "SET_SOCKET",
  SET_GAME_STATE = "SET_GAME_STATE",
  SET_PLAYERS = "SET_PLAYERS",
  SET_ITEMS = "SET_ITEMS",
  SET_IS_DRAGGING = "SET_IS_DRAGGING",
};

export const WHITE_COLOR__HEX = "#FFFFFF";
export const PINK_COLOR__HEX = "#FE13A4";
