export enum reducerCases {
    SET_SOCKET_ID = "SET_SOCKET_ID",
    SET_SPOTIFY_TOKEN = "SET_SPOTIFY_TOKEN",
    SET_PLAYERS = "SET_PLAYERS",
    SET_PLAYER_CARDS = "SET_PLAYER_CARDS",
    SET_OPENED_GAP_INDEX = "SET_OPENED_GAP_INDEX",
    SET_CARDS = "SET_CARDS",
  }