export enum spotifyReducerCases {
    SET_SPOTIFY_PLAYER = "SET_SPOTIFY_PLAYER",
    SET_IS_PLAYING = "SET_IS_PLAYING",
    SET_TIME_POSITION = "SET_TIME_POSITION",
    SET_DURATION = "SET_DURATION",
    SET_VOLUME = "SET_VOLUME",
}