export enum EventResponseStatus {
  ROOM_ID = "ROOM_ID",
  ROOM_STATE = "ROOM_STATE",
  JOIN_ROOM = "JOIN_ROOM",
  UNAUTHORIZED_ACCESS_TOKEN = "UNAUTHORIZED_ACCESS_TOKEN",
  INVALID_GAME_STATUS = "INVALID_GAME_STATUS",
  PLAYER_HOST_CANNOT_BE_REMOVED = "PLAYER_HOST_CANNOT_BE_REMOVED",
  PLAYER_NAME_ALREADY_EXISTS = "PLAYER_NAME_ALREADY_EXISTS",
  PLAYER_COLOR_ALREADY_EXISTS = "PLAYER_COLOR_ALREADY_EXISTS",
  PLAYER_ALREADY_IN_ROOM = "PLAYER_ALREADY_IN_ROOM",
  PLAYLIST_ALREADY_IN_ROOM = "PLAYLIST_ALREADY_IN_ROOM",
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  PLAYLIST_NOT_FOUND = "PLAYLIST_NOT_FOUND",
}

export type EventResponse<T> = {
  success: boolean;
  status: EventResponseStatus;
  code: number;
  data?: T;
  message?: string;
}